version: "3.8"

services:

  sender:
    image: alibi994/sender:1.7
    container_name: sender
    networks: 
      - net1
    depends_on:
      - rabbitmq
    ports:
      - 9090:9090
    restart: on-failure
  
  reciever:
    image: alibi994/reciever:1.7
    container_name: reciever
    networks:
      - net1
    depends_on:
      - rabbitmq
      - postgres
    restart: on-failure
  
  nginx:
    image: nginx:latest
    container_name: nginx
    networks:
      - net1
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/conf.d/default.conf
    depends_on:
      - sender
      - reciever
    restart: on-failure
  
  postgres:
    image: postgres:latest
    container_name: postgres
    networks:
      - net1
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=alireza
      - POSTGRES_DB=template1
    volumes:
      - postgres-vol:/var/lib/postgresql/data
    restart: always

  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    networks:
      - net1
    environment:
      - RABBITMQ_DEFAULT_USER=alireza
      - RABBITMQ_DEFAULT_PASS=1234
    ports:
      - 15672:15672
    restart: always


networks:
  net1:

volumes:
  postgres-vol:
