version: '3.8'

services:

  sender:
    image: alibi994/sender:1.3
    container_name: sender
    networks: 
      - net1
    depends_on:
      - rabbitmq
  
  reciever:
    image: alibi994/reciever:1.3
    container_name: reciever
    networks:
      - net1
    depends_on:
      - rabbitmq
      - postgres
  
  nginx:
    image: nginx:latest
    container_name: nginx
    networks:
      - net1
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/conf.d/default.conf
    depends_on:
      - sender
      - reciever
  
  postgres:
    image: postgres:latest
    container_name: postgres
    networks:
      - net1
    environment:
      - POSTGRES_PASSWORD: 1234
      - POSTGRES_USER: alireza
      - POSTGRES_DB: db1
    volumes:
      - postgres-vol:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    networks:
      - net1
    environment:
      - RABBITMQ_DEFAULT_USER: alireza
      - RABBITMQ_DEFAULT_PASS: 1234
    ports:
      - "15672:15672"


networks:
  net1:

volumes:
  postgres-vol
